<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MiniMVC</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:wght@300;700;800&display=swap" rel="stylesheet">
    <style>
      body {
          font-family: "Public Sans", Arial, sans-serif;
          font-weight: 300;
          font-size:16px;
          color: #313131;
          background-color:cadetblue;
      }

      div.container {
          width:80%;
          margin:auto;
          background-color: antiquewhite;
          padding:1rem;
          border-radius: 1rem;
      }

      nav {
          padding:1rem;
          background-color: #cccccc;
      }

      nav a {
          color: darkblue;
          text-decoration: none;
      }

      img {
          width:128px;
      }

      form {
          background-color:#cccccc;
          width:50%;
          padding:2rem;
          border-radius: 1rem;
          margin:auto;
          margin-top:1rem;
      }

      input {
          margin-top:0.5rem;
      }

    </style>
</head>
<body>
<div class="container">
    <h1>Movie database</h1>
    <nav>
        :nav
    </nav>
    <main>
        :content
    </main>
</div>
</body>
</html>