<?php
//Navigatie
include("nav.phtml");


//Main
$table = "<table>";
foreach($movies as $movie) {
    $image = __DIR__."/images/".$movie['picture'];
    if(!is_dir($image)) {
        $imageData = base64_encode(file_get_contents($image));
        $src = 'data: '.mime_content_type($image).';base64,'.$imageData;
    }
    $table .= "<tr><td><a href='movie/detail/".$movie['movie_id']."'>" . $movie['movie_id'] . "</a></td>";
    $table .= "<td>" . $movie['title'] . "</td>";
    $table .= "<td>" . $movie['year'] . "</td>";
    $table .= "<td><img src='".$src."' alt='".$movie['picture']."'></td>";
    $table .= "<td><a href='/movie/delete/" . $movie['movie_id'] . "'>delete</a></td></tr>";
}
$table .= "</table>";

$render[':content'] = $table;


?>
