<?php

include("nav.phtml");



//Main
$html = "<ul>";
$image = __DIR__."/images/".$movie['picture'];
if(!is_dir($image)) {
    $imageData = base64_encode(file_get_contents($image));
    $src = 'data: '.mime_content_type($image).';base64,'.$imageData;
}
$html .= "<li>" . $movie['title'] . "</li>";
$html .= "<li>" . $movie['year'] . "</li>";
$html .= "<li><img src='".$src."' alt='".$movie['picture']."'></li>";

$html .= "</ul>";

$render[':content'] = $html;


?>
